### ISSUE TITLE
fails to open. i drag file into window, league momentarily opens, but then it crashes and a bunch of crash report code comes up.

### ISSUE THREAD

**Issue by bestusernamena** [genesor/OPGG_Spectate_Mac#24]

**Comment by genesor** [comment]
Can you give me more details ?

**Comment by SpooksEU** [comment]
I have a problem that sounds a lot like this one. 

I downloaded your app earlier today, and the first few times it worked as intended. 
But now it's failing to recognize when i have dropped a replay file over the target area, and when i finally get it to work(by trying multiple times), it opens the client on a black screen and after a while an error pops up: "Connection to spectator server failed. Would you like to retry?" - Nothing happens when i press retry. 

the problem with the app not getting to recognize the file started after i tryed to rename some of the replay files i downloaded from op.gg. - Later when i then tryed with another (not renamed) version of the file, it started to give me the black screen. Maybe it can have something to do with the new patch they announced this evening?
